apiVersion: v1
kind: Service
metadata:
  name: altobot-service
  labels:
    name:  altobot-service
    app: altobot-app
spec:
  type: NodePort
  selector:
    name: altobot-pod
    app: altobot-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30008